### PR TITLE
fix: internal provider comparison causing race conditions in tests

### LINKED ISSUE #307: [BUG] Data race if the provider set few times
### Observed behavior

I have several tests with a similar setup: the provider is created, then configured, the tests are executed, and `openfeature.Shutdown()` is called for cleanup. However, when these tests are run with the race detector enabled, they consistently fail.

### Expected Behavior

_No response_

### Steps to reproduce

```go
package openfeature_test

import (
	"context"
	"sync"
	"testing"

	of "github.com/open-feature/go-sdk/openfeature"
)

func TestDataRace(t *testing.T) {
	of.SetEvaluationContext(of.NewTargetlessEvaluationContext(map[string]any{}))

	err := of.SetProviderAndWait(newRaceProvider())
	if err != nil {
		t.Fatal(err)
	}

	of.Shutdown()

	err = of.SetProviderAndWait(newRaceProvider())
	if err != nil {
		t.Fatal(err)
	}
}

func newRaceProvider() of.FeatureProvider {
	return &raceProvider{
		state: of.NotReadyState,
	}
}

var (
	_ of.FeatureProvider = (*raceProvider)(nil) // ensure implements FeatureProvider
	_ of.StateHandler    = (*raceProvider)(nil) // ensure implements StateHandler
)

type raceProvider struct {
	state of.State
	mu    sync.RWMutex
}

func (p *raceProvider) Metadata() of.Metadata {
	return of.Metadata{
		Name: "racing",
	}
}

func (p *raceProvider) Status() of.State {
	p.mu.RLock()
	defer p.mu.RUnlock()

	return p.state
}

func (p *raceProvider) Init(evalCtx of.EvaluationContext) error {
	p.mu.Lock()
	defer p.mu.Unlock()
	p.state = of.ReadyState
	return nil
}

func (p *raceProvider) Shutdown() {
	p.mu.Lock()
	defer p.mu.Unlock()
	p.state = of.NotReadyState
}

func (p *raceProvider) BooleanEvaluation(ctx context.Context, flag string, defaultValue bool, evalCtx of.FlattenedContext) of.BoolResolutionDetail {
	return of.BoolResolutionDetail{}
}

func (p *raceProvider) StringEvaluation(ctx context.Context, flag string, defaultValue string, evalCtx of.FlattenedContext) of.StringResolutionDetail {
	return of.StringResolutionDetail{}
}

func (p *raceProvider) FloatEvaluation(ctx context.Context, flag string, defaultValue float64, evalCtx of.FlattenedContext) of.FloatResolutionDetail {
	return of.FloatResolutionDetail{}
}

func (p *raceProvider) IntEvaluation(ctx context.Context, flag string, defaultValue int64, evalCtx of.FlattenedContext) of.IntResolutionDetail {
	return of.IntResolutionDetail{}
}

func (p *raceProvider) ObjectEvaluation(ctx context.Context, flag string, defaultValue interface{}, evalCtx of.FlattenedContext) of.InterfaceResolutionDetail {
	return of.InterfaceResolutionDetail{}
}

func (p *raceProvider) Hooks() []of.Hook {
	return []of.Hook{}
}
```

Create a file with test and run `go test -race ./...`

### PR DESCRIPTION
**Pull request by warber**
## This PR
This pull request addresses issue #307 by comparing FeatureProvider implementations internally using their pointer addresses. It inspects the FeatureProvider provided by the user and uses the == operator for comparison if dealing with pointers. Otherwise, it utilizes the existing deepEquals comparison.

### Related Issues

Fixes #307

### CODE REVIEW

File: openfeature/reference_test.go [hunk 1]
```diff
@@ -0,0 +1,68 @@
...
+			name:     "Both pointers, different instances",
+			pr1:      newProviderRef(&p1),
+			pr2:      newProviderRef(&p2),
+			expected: false,
+		},
+		{
+			name:     "Both pointers, same instance",
+			pr1:      newProviderRef(&p1),
+			pr2:      newProviderRef(&p1),
+			expected: false,
```
Comment (erka) [inline openfeature/reference_test.go:33]: it should be true, right?

**Comment by toddbaert** [comment]
@warber I think this solution solves the whole issue without putting constraints on the user, yes? IIUC, with this we:

- can compare providers reliably, whether they are pointers or structs :heavy_check_mark: 
- can avoid locking on the shutdown :heavy_check_mark: 
- don't have any public-facing API changes :heavy_check_mark: 

Correct?

**Comment by beeme1mr** [comment]
Hey @warber, is this still a work-in-progress or can it be reviewed now?

**Comment by warber** [comment]
> Hey @warber, is this still a work-in-progress or can it be reviewed now?

@beeme1mr it's ready for review

**Review by aepfli — APPROVED** [review]

**Review by erka — APPROVED** [review]

**Review by thomaspoignant — APPROVED** [review]

**Review by toddbaert — APPROVED** [review]
Looks good. I can confirm I can't reproduce and sort of race with this as well. Thanks a lot @warber and @erka .

I will release this today unless there are objections.
